I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/tutorial.rpy", line 270, in script
    python:
  File "game/tutorial.rpy", line 272, in <module>
    if achievementList[17] == False:
IndexError: list index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/tutorial.rpy", line 270, in script
    python:
  File "renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/tutorial.rpy", line 272, in <module>
    if achievementList[17] == False:
  File "renpy/python.py", line 992, in __getitem__
    rv = list.__getitem__(self, index)
IndexError: list index out of range

Windows-10-10.0.19041
Ren'Py 7.4.10.2178
Beta 1.0
Sun Nov 21 19:05:36 2021
